# Generated by Django 5.1.7 on 2025-03-30 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeTai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_de_tai', models.CharField(max_length=10, unique=True)),
                ('ten_de_tai', models.CharField(max_length=200, unique=True)),
                ('so_luong_toi_da', models.PositiveIntegerField(default=3)),
            ],
        ),
        migrations.CreateModel(
            name='GiangVien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_giang_vien', models.CharField(max_length=10, unique=True)),
                ('ho_ten', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('so_dien_thoai', models.CharField(max_length=15)),
                ('khoa', models.CharField(max_length=50)),
                ('chuc_vu', models.CharField(blank=True, max_length=50, null=True)),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('so_luong_toi_da', models.PositiveIntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='SinhVien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_sinh_vien', models.CharField(max_length=255, unique=True)),
                ('ho_ten', models.CharField(max_length=100)),
                ('so_tin_chi_da_dat', models.PositiveIntegerField(default=0)),
                ('gpa', models.FloatField(default=0.0)),
                ('co_no_mon', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DoAn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('de_tai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='do_an', to='home.detai')),
                ('giang_vien_huong_dan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='do_an_set', to='home.giangvien')),
                ('sinh_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='do_an_sinh_vien', to='home.sinhvien')),
            ],
        ),
        migrations.CreateModel(
            name='HoiDongCham',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_hoi_dong', models.CharField(max_length=100, unique=True)),
                ('giang_vien', models.ManyToManyField(related_name='hoi_dong', to='home.giangvien')),
            ],
        ),
        migrations.CreateModel(
            name='LichBaoVe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('do_an', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lich_bao_ve', to='home.doan')),
                ('hoi_dong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lich_bao_ve', to='home.hoidongcham')),
            ],
        ),
    ]
